# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SOAP-Integr8
version:      1.0
version_from: lib/SOAP/Integr8.pm
installdirs:  site
requires:
    SOAP::Lite:                    
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
